[features]
seeds = false
skip-lint = false

[programs.localnet]
meteor_route_fee_router = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
cp_amm = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
