[features]
seeds = false
skip-lint = false

[programs.localnet]
meteor_route_fee_router = "BK5eKYpvFhvnVTDX6ZV6zcpkAgmKTiSi2Q8z9ypGR23E"
cp_amm = "9A8togt7c2wkR2putRLZ9vthcwX93wrnGij8W7sZZHFr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
